apiVersion: apps/v1
kind: Deployment
metadata:
  name: 7p-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 7p-app
  template:
    metadata:
      labels:
        app: 7p-app
    spec:
      containers:
        - name: minikube
          image: 7p-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
